package ch.uzh.ifi.ce.domain;

public enum ValueType {
    CATS, UNDEFINED, SUPER_SMALL, SMALL, MEDIUM, LARGE, SUPER_LARGE, LOCAL, GLOBAL, EAST, LOCAL_WEST, LOCAL_CENTER, LOCAL_EAST, GLOBAL_WEST, GLOBAL_EAST
}
